/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sanodmendis.bxbyn.movements;

import com.sanodmendis.bxbyn.database.DBConnection;
import com.sanodmendis.bxbyn.database.DBHelper;
import com.sanodmendis.bxbyn.models.MovementHeader;
import com.sanodmendis.bxbyn.models.MovementItem;
import com.sanodmendis.bxbyn.models.POItem;
import com.sanodmendis.bxbyn.models.PurchaseOrder;
import com.sanodmendis.bxbyn.utils.StatusMessageHandler;

import javax.swing.ImageIcon;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Sanod D. Mendis
 */
public class formIN11 extends javax.swing.JFrame {

    /**
     * Creates new form formIN11
     */
    private PurchaseOrder currentPO;
    private List<POItem> poItems;
    private MovementHeader currentMovement;
    private String currentUser = "ADMIN";
    private DefaultTableModel tableModel;

    public formIN11() {
        initComponents();
        DBConnection.setStatusField(txtStatus);
        initializeData();
        tableModel = (DefaultTableModel) jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPONumber = new javax.swing.JTextField();
        btnSearchPO = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtMovementNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtVendor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDeliveryNote = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbPutawayBin = new javax.swing.JComboBox<>();
        chkQualityCheck = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        tblPOItems = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnAddItem = new javax.swing.JButton();
        btnPostGR = new javax.swing.JButton();
        btnCreatePutaway = new javax.swing.JButton();
        btnCancelGR = new javax.swing.JButton();
        txtStatus = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GR Purchase Order");
        setIconImage(new ImageIcon(getClass().getResource("/icons/app.png")).getImage());
        setMinimumSize(new java.awt.Dimension(920, 640));

        headerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Purchase Order Details"));

        jLabel1.setText("PO Number");

        btnSearchPO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black-search.png"))); // NOI18N
        btnSearchPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPOActionPerformed(evt);
            }
        });

        jLabel2.setText("Movement #:");

        txtMovementNumber.setEditable(false);

        jLabel3.setText("Vendor:");

        txtVendor.setEditable(false);

        jLabel4.setText("Delivery Note:");

        txtDeliveryNote.setEditable(false);

        jLabel5.setText("Putaway Bin:");

        cmbPutawayBin.setEditable(true);

        chkQualityCheck.setText("Quality Check Required");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPONumber, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVendor)))
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchPO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMovementNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDeliveryNote, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbPutawayBin, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chkQualityCheck)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchPO)
                    .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtPONumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtMovementNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtDeliveryNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(cmbPutawayBin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chkQualityCheck))
                    .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtVendor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("PO Items"));

        tblPOItems.setName("tblPOItems"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Material Code", "Material Description", "Ordered Qty", "Received Qty", "This Receipt", "Batch", "UOM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPOItems.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tblPOItems)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tblPOItems, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        btnAddItem.setText("Add Item");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        btnPostGR.setText("Post GR");
        btnPostGR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostGRActionPerformed(evt);
            }
        });

        btnCreatePutaway.setText("Create Putaway");
        btnCreatePutaway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePutawayActionPerformed(evt);
            }
        });

        btnCancelGR.setText("Cancel GR");
        btnCancelGR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelGRActionPerformed(evt);
            }
        });

        txtStatus.setEditable(false);
        txtStatus.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtStatus.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(btnAddItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPostGR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreatePutaway)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelGR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtStatus)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddItem)
                    .addComponent(btnPostGR)
                    .addComponent(btnCreatePutaway)
                    .addComponent(btnCancelGR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        // TODO add your handling code here:
        addManualItem();
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnSearchPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPOActionPerformed
        // TODO add your handling code here:
        searchPurchaseOrder();
    }//GEN-LAST:event_btnSearchPOActionPerformed

    private void btnPostGRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostGRActionPerformed
        // TODO add your handling code here:
        postGoodsReceipt();
    }//GEN-LAST:event_btnPostGRActionPerformed

    private void btnCancelGRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelGRActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelGRActionPerformed

    private void btnCreatePutawayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePutawayActionPerformed
        // TODO add your handling code here:
        createPutawayTO();
    }//GEN-LAST:event_btnCreatePutawayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formIN11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formIN11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formIN11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formIN11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formIN11().setVisible(true);
            }
        });
    }

    private void initializeData() {
        try {
            String movementNumber = DBHelper.getNextMovementNumber();
            txtMovementNumber.setText(movementNumber);
            loadPutawayBins();
        } catch (SQLException e) {
            StatusMessageHandler.showError(txtStatus, "Error initializing form: " + e.getMessage());
        }
    }

    private void loadPutawayBins() {
        try {
            String query = "SELECT bin_code FROM storage_bins WHERE bin_type = 'RECEIVING' AND is_active = TRUE";
            ResultSet rs = DBHelper.executeQuery(query);

            cmbPutawayBin.removeAllItems();
            while (rs.next()) {
                cmbPutawayBin.addItem(rs.getString("bin_code"));
            }

            if (cmbPutawayBin.getItemCount() > 0) {
                cmbPutawayBin.setSelectedIndex(0);
            }
        } catch (SQLException e) {
            StatusMessageHandler.showError(txtStatus, "Error loading bins: " + e.getMessage());
        }
    }

    private void searchPurchaseOrder() {
        String poNumber = txtPONumber.getText().trim();
        if (poNumber.isEmpty()) {
            StatusMessageHandler.showWarning(txtStatus, "Please enter a PO Number");
            return;
        }

        try {
            String query = "SELECT po_number, vendor, order_date FROM purchase_orders WHERE po_number = ? AND status = 'OPEN'";
            ResultSet rs = DBHelper.executeQuery(query, poNumber);

            if (rs.next()) {
                currentPO = new PurchaseOrder();
                currentPO.setPoNumber(rs.getString("po_number"));
                currentPO.setVendor(rs.getString("vendor"));
                txtVendor.setText(rs.getString("vendor"));

                loadPOItems(poNumber);
                btnPostGR.setEnabled(true);
                StatusMessageHandler.showSuccess(txtStatus, "PO loaded successfully: " + poNumber);
            } else {
                StatusMessageHandler.showWarning(txtStatus, "PO not found or not open: " + poNumber);
            }
        } catch (SQLException e) {
            StatusMessageHandler.showError(txtStatus, "Error searching PO: " + e.getMessage());
        }
    }

    private void loadPOItems(String poNumber) {
        try {
            String query = "SELECT pi.material_id, m.material_code, m.material_description, "
                    + "pi.ordered_quantity, pi.received_quantity, m.base_uom "
                    + "FROM po_items pi "
                    + "JOIN materials m ON pi.material_id = m.material_id "
                    + "WHERE pi.po_number = ? AND (pi.ordered_quantity - pi.received_quantity) > 0";

            ResultSet rs = DBHelper.executeQuery(query, poNumber);

            tableModel.setRowCount(0);
            poItems = new ArrayList<>();

            while (rs.next()) {
                POItem item = new POItem();
                item.setPoNumber(poNumber);
                item.setMaterialId(rs.getInt("material_id"));
                item.setMaterialCode(rs.getString("material_code"));
                item.setMaterialDescription(rs.getString("material_description"));
                item.setOrderedQty(rs.getBigDecimal("ordered_quantity"));
                item.setReceivedQty(rs.getBigDecimal("received_quantity"));
                item.setUom(rs.getString("base_uom"));

                poItems.add(item);

                Object[] row = {
                    item.getMaterialCode(),
                    item.getMaterialDescription(),
                    item.getOrderedQty(),
                    item.getReceivedQty(),
                    BigDecimal.ZERO,
                    "",
                    item.getUom()
                };
                tableModel.addRow(row);
            }

            if (poItems.isEmpty()) {
                StatusMessageHandler.showError(txtStatus, "No open items found for this PO");
            }
        } catch (SQLException e) {
            StatusMessageHandler.showError(txtStatus, "Error loading PO items: " + e.getMessage());
        }
    }

    private void addManualItem() {
        StatusMessageHandler.showInfo(txtStatus, "Manual item addition feature to be implemented");
    }

    private boolean validateGRInputs() {
        boolean hasReceipt = false;
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            Object receiptValue = tableModel.getValueAt(i, 4);
            if (receiptValue != null && !receiptValue.toString().isEmpty()) {
                BigDecimal receipt = new BigDecimal(receiptValue.toString());
                if (receipt.compareTo(BigDecimal.ZERO) > 0) {
                    hasReceipt = true;
                    break;
                }
            }
        }

        if (!hasReceipt) {
            StatusMessageHandler.showWarning(txtStatus, "Please enter receipt quantities for at least one item");
            return false;
        }

        if (cmbPutawayBin.getSelectedItem() == null) {
            StatusMessageHandler.showWarning(txtStatus, "Please select a putaway bin");
            return false;
        }

        return true;
    }

    private void postGoodsReceipt() {
        if (!validateGRInputs()) {
            return;
        }

        try {
            DBHelper.startTransaction();

            MovementHeader movement = new MovementHeader(
                    txtMovementNumber.getText(),
                    1,
                    txtPONumber.getText(),
                    currentUser
            );
            movement.setNotes("GR for PO: " + txtPONumber.getText() + ", Delivery Note: " + txtDeliveryNote.getText());

            String insertHeader = "INSERT INTO movement_headers (movement_number, movement_type_id, reference_document, "
                    + "movement_date, status, created_by, created_date, notes) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

            DBHelper.executeUpdate(insertHeader,
                    movement.getMovementNumber(),
                    movement.getMovementTypeId(),
                    movement.getReferenceDocument(),
                    movement.getMovementDate(),
                    movement.getStatus(),
                    movement.getCreatedBy(),
                    movement.getCreatedDate(),
                    movement.getNotes()
            );

            ResultSet rs = DBHelper.executeQuery("SELECT LAST_INSERT_ID()");
            rs.next();
            int movementId = rs.getInt(1);

            for (int i = 0; i < tableModel.getRowCount(); i++) {
                BigDecimal thisReceipt = new BigDecimal(tableModel.getValueAt(i, 4).toString());
                if (thisReceipt.compareTo(BigDecimal.ZERO) > 0) {
                    String materialCode = tableModel.getValueAt(i, 0).toString();

                    ResultSet materialRs = DBHelper.executeQuery("SELECT material_id FROM materials WHERE material_code = ?", materialCode);
                    materialRs.next();
                    int materialId = materialRs.getInt("material_id");

                    Integer batchId = null;
                    String batchNumber = tableModel.getValueAt(i, 5).toString();
                    if (!batchNumber.isEmpty()) {
                        ResultSet batchRs = DBHelper.executeQuery(
                                "SELECT batch_id FROM material_batches WHERE batch_number = ? AND material_id = ?",
                                batchNumber, materialId
                        );
                        if (batchRs.next()) {
                            batchId = batchRs.getInt("batch_id");
                        } else {
                            String insertBatch = "INSERT INTO material_batches (material_id, batch_number) VALUES (?, ?)";
                            DBHelper.executeUpdate(insertBatch, materialId, batchNumber);

                            ResultSet newBatchRs = DBHelper.executeQuery("SELECT LAST_INSERT_ID()");
                            newBatchRs.next();
                            batchId = newBatchRs.getInt(1);
                        }
                    }

                    String binCode = cmbPutawayBin.getSelectedItem().toString();
                    ResultSet binRs = DBHelper.executeQuery("SELECT bin_id FROM storage_bins WHERE bin_code = ?", binCode);
                    binRs.next();
                    int toBinId = binRs.getInt("bin_id");

                    String insertItem = "INSERT INTO movement_items (movement_id, material_id, batch_id, to_bin_id, "
                            + "quantity, uom, line_status, processed_quantity) "
                            + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

                    DBHelper.executeUpdate(insertItem,
                            movementId,
                            materialId,
                            batchId,
                            toBinId,
                            thisReceipt,
                            tableModel.getValueAt(i, 6).toString(),
                            "COMPLETED",
                            thisReceipt
                    );

                    updateInventory(materialId, batchId, toBinId, thisReceipt);
                    updatePOReceivedQty(materialId, thisReceipt);
                }
            }

            String updateHeader = "UPDATE movement_headers SET status = 'POSTED', posted_by = ?, posted_date = ? WHERE movement_id = ?";
            DBHelper.executeUpdate(updateHeader, currentUser, LocalDateTime.now(), movementId);

            DBHelper.commitTransaction();

            StatusMessageHandler.showSuccess(txtStatus, "Goods Receipt posted successfully! Movement: " + movement.getMovementNumber());

            btnCreatePutaway.setEnabled(true);
            btnPostGR.setEnabled(false);

        } catch (SQLException e) {
            try {
                DBHelper.rollbackTransaction();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            StatusMessageHandler.showError(txtStatus, "Error posting GR: " + e.getMessage());
        }
    }

    private void updateInventory(int materialId, Integer batchId, int binId, BigDecimal quantity) throws SQLException {
        String checkQuery = "SELECT inventory_id, quantity FROM inventory WHERE material_id = ? AND bin_id = ? "
                + (batchId != null ? "AND batch_id = ?" : "AND batch_id IS NULL");

        ResultSet rs;
        if (batchId != null) {
            rs = DBHelper.executeQuery(checkQuery, materialId, binId, batchId);
        } else {
            rs = DBHelper.executeQuery(checkQuery, materialId, binId);
        }

        if (rs.next()) {
            BigDecimal currentQty = rs.getBigDecimal("quantity");
            BigDecimal newQty = currentQty.add(quantity);

            String updateQuery = "UPDATE inventory SET quantity = ?, available_quantity = ?, last_movement_date = NOW() "
                    + "WHERE inventory_id = ?";
            DBHelper.executeUpdate(updateQuery, newQty, newQty, rs.getInt("inventory_id"));
        } else {
            String insertQuery = "INSERT INTO inventory (material_id, batch_id, bin_id, quantity, available_quantity, last_movement_date) "
                    + "VALUES (?, ?, ?, ?, ?, NOW())";
            DBHelper.executeUpdate(insertQuery, materialId, batchId, binId, quantity, quantity);
        }
    }

    private void updatePOReceivedQty(int materialId, BigDecimal receiptQty) throws SQLException {
        String updateQuery = "UPDATE po_items SET received_quantity = received_quantity + ? "
                + "WHERE po_number = ? AND material_id = ?";
        DBHelper.executeUpdate(updateQuery, receiptQty, txtPONumber.getText(), materialId);
    }

    private void createPutawayTO() {
        StatusMessageHandler.showInfo(txtStatus, "Putaway TO creation feature to be implemented");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnCancelGR;
    private javax.swing.JButton btnCreatePutaway;
    private javax.swing.JButton btnPostGR;
    private javax.swing.JButton btnSearchPO;
    private javax.swing.JCheckBox chkQualityCheck;
    private javax.swing.JComboBox<String> cmbPutawayBin;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane tblPOItems;
    private javax.swing.JTextField txtDeliveryNote;
    private javax.swing.JTextField txtMovementNumber;
    private javax.swing.JTextField txtPONumber;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtVendor;
    // End of variables declaration//GEN-END:variables
}